name: Python Version Check

on: [push]

jobs:
  check-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Uses the latest stable 3.x version

    - name: Check Python version
      run: |
        python --version
        python -c "import sys; print(f'Full version: {sys.version}')"