name: Build, Test, and Deploy Python App

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # or your specific version like '3.9'
          cache: 'pip' # caches pip dependencies
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: python -m pytest
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: .

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: python-app
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # or your app name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: 'main'
          usedocker: false
          healthcheck: 'https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/'
          checkstring: 'ok'
          delay: 5
          rollbackonhealthcheckfailed: true