name: Simple Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cfd
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Wait for PostgreSQL
      run: |
        timeout 60 bash -c 'until pg_isready; do sleep 1; done'
        sleep 5  # Extra buffer time
        
    - name: Build and test
      run: mvn -B verify